package com.lab.bracketlab.processing.align.star

enum class StarMatchingFailureCode {
    EMPTY_CATALOG_SET,
    INVALID_CATALOG,
    NO_REFERENCE_CATALOG,
    TOO_FEW_REFERENCE_STARS,
    TOO_FEW_TARGET_STARS,
    NO_MATCH_CANDIDATES,
    AMBIGUOUS_MATCHES,
    RANSAC_FAILED,
    TOO_FEW_INLIERS,
    LOW_INLIER_RATIO,
    EXCESSIVE_RMS_ERROR,
    DEGENERATE_GEOMETRY,
    INSUFFICIENT_SPATIAL_COVERAGE,
    EXCESSIVE_TRANSLATION,
    EXCESSIVE_ROTATION,
    INVALID_SCALE,
    NON_FINITE_TRANSFORM,
    MATCHING_FAILED,
    REPORT_WRITE_FAILED
}

enum class StarMatchingStrategy {
    IDENTITY,
    SMALL_MOTION,
    GEOMETRIC_PATTERN,
    NONE
}

enum class StarReferenceSelectionReason {
    ONLY_CATALOG,
    MIDDLE_CATALOG,
    NEAREST_STRONG_CATALOG_FALLBACK
}
