package com.lab.bracketlab.processing.hdri

enum class HdrI32FailureCode {
    EMPTY_HDR_STACK,
    INSUFFICIENT_HDR_FRAMES,
    IDENTICAL_EXPOSURE_SET,
    INVALID_EXPOSURE_TIME,
    INCOMPATIBLE_DIMENSIONS,
    INCOMPATIBLE_CFA,
    INCOMPATIBLE_CAMERA,
    INCOMPATIBLE_ISO,
    INCOMPATIBLE_BLACK_LEVEL,
    INCOMPATIBLE_WHITE_LEVEL,
    INVALID_RAW_STORAGE,
    NO_VALID_HDR_SAMPLE,
    HDRI_TEMP_FILE_FAILURE,
    HDRI_PROCESSING_FAILED,
    HDRI_STORAGE_FAILED,
    XISF_WRITE_FAILED,
    FITS_WRITE_FAILED,
    LINEAR_RGB_FLOAT16_DNG_FAILED,
    INSUFFICIENT_STORAGE,
    INVALID_ALIGNMENT_REPORT
}

enum class HdrI32WarningCode {
    DARK_CALIBRATION_DISABLED_FOR_HDRI,
    HDRI_ALIGNMENT_IDENTITY_ONLY,
    HDRI_ALIGNMENT_LANDSCAPE_TRANSLATION,
    SATURATED_SAMPLE_FALLBACK_USED,
    IDENTICAL_EXPOSURE_SET_ALLOWED
}

data class HdrI32Warning(
    val code: HdrI32WarningCode,
    val message: String
)
