package com.lab.bracketlab.processing.io

enum class Raw16DngFailureCode {
    INVALID_STACK_RESULT,
    STACK_RESULT_NOT_SUCCESSFUL,
    INVALID_OUTPUT_DIMENSIONS,
    BUFFER_SIZE_MISMATCH,
    UNSUPPORTED_ROW_STRIDE,
    UNSUPPORTED_PIXEL_STRIDE,
    INVALID_BYTE_ORDER,
    MISSING_CAMERA_CHARACTERISTICS,
    MISSING_CAPTURE_RESULT,
    MISSING_REFERENCE_METADATA,
    REFERENCE_METADATA_MISMATCH,
    METADATA_SIZE_MISMATCH,
    SENSOR_ACTIVE_ARRAY_MISMATCH,
    REFERENCE_FRAME_SIZE_MISMATCH,
    DNGCREATOR_ILLEGAL_STATE,
    DNGCREATOR_ILLEGAL_ARGUMENT,
    OUTPUT_IO_FAILURE,
    OUTPUT_PERMISSION_FAILURE,
    DESTINATION_CREATION_FAILED,
    OUTPUT_COMMIT_FAILED,
    PARTIAL_OUTPUT_CLEANUP_FAILED,
    PIPELINE_ALIGNMENT_FAILED,
    PIPELINE_STACKING_FAILED,
    PIPELINE_METADATA_FAILED,
    PIPELINE_WRITING_FAILED
}

enum class Raw16DngWarningCode {
    BORDER_HAS_REDUCED_SAMPLE_COUNT,
    CFA_SAFE_TRANSLATION_RESIDUAL_PRESENT,
    LOW_ALIGNMENT_CONFIDENCE_ACCEPTED,
    REJECTED_FRAMES_EXCLUDED,
    DESCRIPTION_TRUNCATED,
    THUMBNAIL_NOT_INCLUDED,
    OUTPUT_FILE_RENAMED_TO_AVOID_COLLISION,
    SENSOR_ACTIVE_ARRAY_DIFFERS_FROM_RAW_SIZE,
    PRE_CORRECTION_ACTIVE_ARRAY_DIFFERS_FROM_RAW_SIZE,
    TEMPORARY_RAW_CLEANUP_FAILED
}

enum class Raw16DngWriterMethod {
    BYTE_BUFFER,
    INPUT_STREAM
}

enum class Raw16DngCleanupResult {
    NOT_NEEDED,
    CLEANED_UP,
    CLEANUP_FAILED,
    NOT_ATTEMPTED
}

data class Raw16DngWarning(
    val code: Raw16DngWarningCode,
    val message: String
)
